---
title: "Assignment 2"
author: "Pranav Belmannu, Maithilee Kulkarni, Lea Stavoli, Swetha Vangapandu"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

```{r libraries}
library(tidyverse)
library(ggplot2)
library(lubridate)
library(reshape2)
library(corrplot)
```

```{r load files}
LS_path <- "/Volumes/My Passport/MS Business Analytics/FINC780/"

#Consumer Sentiment Index https://data.sca.isr.umich.edu/data-archive/mine.php
index_file <- paste(LS_path,"Index_Consumer_Sentiment_2022_Nov_11.csv", sep="")

#Fed Rate https://fred.stlouisfed.org/series/FEDFUNDS
fed_rate_file <- paste(LS_path, "Federal_Funds_Effective_Rate_2008_to_2022.csv", sep="")

#GSPC from Yahoo Finance
GSPC_file <- paste(LS_path, "GSPC_2008_to_2022.csv", sep="")

#US Bureau of Labor Statistics (following 3 files)
#Average hourly earnings of all employees, total private, seasonally adjusted
hourly_earnings_file <- paste(LS_path, "Avg_Hourly_Earnings_2008_to_2022.csv", sep="")

#Consumer Price Index
#All items in U.S. city average, all urban consumers, seasonally adjusted
CPI_file <- paste(LS_path, "Consumer_Price_Index_2008_to_2022.csv", sep="")

#Unemployment rate
unemployment_file <- paste(LS_path, "Unemployment_Rate_2008_to_2022.csv", sep="")
```

```{r}
#read-in consumer sentiment index file
#delete leading rows, rename columns, delete extra [blank] column
index_df <- read.csv(index_file,header=F)
colnames(index_df) <- c('Month','Year','Index','V')
index_df <- index_df %>% filter(!row_number() %in% c(1, 2))
index_df <- index_df[,1:3]
head(index_df)

#check data formats
str(index_df)

#create date column, set as index
index_df$Date <- paste(index_df$Month, "-",index_df$Year, sep = "")
index_df$Date <- my(index_df$Date)
rownames(index_df) <- index_df$Date
index_df <- index_df["Index"]

#format index as a number
index_df$Index <- as.double(index_df$Index)
```

```{r}
#read-in fed rate file
fed_rate_df <- read.csv(fed_rate_file)
head(fed_rate_df)

#check data formats
str(fed_rate_df)

#format date column, set as index
fed_rate_df$DATE <- ymd(fed_rate_df$DATE)
rownames(fed_rate_df) <- fed_rate_df$DATE
fed_rate_df$DATE <- NULL
```

```{r}
#read-in GSPC file
GSPC_df <- read.csv(GSPC_file)
head(GSPC_df)

#check data formats
str(GSPC_df)

#format date column
GSPC_df$Date <- dmy(GSPC_df$Date)
```

```{r}
#read-in hourly earnings file
hourly_earnings_df <- read.csv(hourly_earnings_file)
head(hourly_earnings_df)

#melt to long format
hourly_earnings_df <- melt(hourly_earnings_df, id.vars = "Year", value.name = "Hr.Rate")

#check data formats
str(hourly_earnings_df)

#format date column, set as index
hourly_earnings_df$Date <- paste(hourly_earnings_df$variable, "-",hourly_earnings_df$Year, sep = "")
hourly_earnings_df$Date <- my(hourly_earnings_df$Date)
rownames(hourly_earnings_df) <- hourly_earnings_df$Date
hourly_earnings_df <- hourly_earnings_df["Hr.Rate"]
```

```{r}
#read-in consumer pricing index file
CPI_df <- read.csv(CPI_file)
head(CPI_df)

#melt to long format
CPI_df <- melt(CPI_df, id.vars = "Year", value.name = "CPI")

#check data formats
str(CPI_df)

#format date column, set as index
CPI_df$Date <- paste(CPI_df$variable, "-",CPI_df$Year, sep = "")
CPI_df$Date <- my(CPI_df$Date)
rownames(CPI_df) <- CPI_df$Date
CPI_df <- CPI_df["CPI"]
```

```{r}
#read-in unemployment file
unemployment_df <- read.csv(unemployment_file)
head(unemployment_df)

#melt to long format
unemployment_df <- melt(unemployment_df, id.vars = "Year", value.name = "Unemp")

#check data formats
str(unemployment_df)

#format date column, set as index
unemployment_df$Date <- paste(unemployment_df$variable, "-",unemployment_df$Year, sep = "")
unemployment_df$Date <- my(unemployment_df$Date)
rownames(unemployment_df) <- unemployment_df$Date
unemployment_df <- unemployment_df["Unemp"]
```

```{r}
#merge Bureau of Labor Statistics dfs by index (row names)
stats_df <- merge(hourly_earnings_df, CPI_df, by = "row.names", all = TRUE)

#add unemployment
stats_df <- merge(stats_df, unemployment_df, by.x = "Row.names", by.y = "row.names", all = TRUE)
```

```{r}
#merge stats with consumer sentiment index, drop rows with na values
df <- merge(index_df, stats_df, by.x = "row.names", by.y = "Row.names", all = TRUE)

#merge fed rate, drop rows with na values
df <- merge(df, fed_rate_df, by.x = "Row.names", by.y = "row.names", all = TRUE)
head(df)

df <- df %>% drop_na()
```

```{r}
#update date column, create Year to group_by to find annual mean
df$Row.names <- ymd(df$Row.names)
df$Year <- year(df$Row.names)
head(df)
```

```{r}
#correlation matrix & plot of Index & BLS data
#Unemp is highly negatively correlated
#average hourly rate, consumer pricing index, and fed rate seem moderately correlated to the index
df_corr <- cor(df[c("Index", "Hr.Rate", "CPI", "Unemp", "FEDFUNDS")])
df_corr
```

```{r}
#plot correlation matrix
corrplot(df_corr, method = 'color', col = COL2('PRGn'), diag = FALSE)
```

```{r}
#plot index
ggplot(df, aes(x = Row.names, y = Index)) +
  geom_line(color = "blue") +
  ggtitle("Consumer Sentiment Index 2008 - 2022")
```

```{r}
#plot Hr.Rate
ggplot(df, aes(x = Row.names, y = Hr.Rate)) +
  geom_line(color = "green") +
  ggtitle("Average Hourly Earnings 2008 - 2022")
```

```{r}
#plot CPI
ggplot(df, aes(x = Row.names, y = CPI)) +
  geom_line(color = "orange") +
  ggtitle("Consumer Pricing Index 2008 - 2022")
```

```{r}
#plot unemployment
ggplot(df, aes(x = Row.names, y = Unemp)) +
  geom_line(color = "red") +
  ggtitle("Unemployment Rate 2008 - 2022")
```

```{r}
#plot fed rate
ggplot(df, aes(x = Row.names, y = FEDFUNDS)) +
  geom_line(color = "magenta") +
  ggtitle("Federal Funds Effective Rate 2008 - 2022")
```

```{r}
#make long format, plot all stats
long_df <- subset(df, select = -c(Year))
long_df <- melt(long_df, id = "Row.names")

ggplot(long_df, aes(x = Row.names, y = value, color = variable)) +
  geom_line() + 
  ggtitle("Consumer Sentiment Index Compared to BLS Data 2008 - 2022")
```

```{r}
#plot GSPC
ggplot(GSPC_df, aes(x = Date, y = Adj.Close)) +
  geom_line() +
  ggtitle("GSPC 2008 - 2022")
```

```{r}
#summarize data by year & merge with GSPC to plot
group_df <- df %>% group_by(Year) %>% 
  summarize(mean_index = mean(Index),
            mean_hr_rate = mean(Hr.Rate),
            mean_CPI = mean(CPI),
            mean_unemp = mean(Unemp),
            mean_fed = mean(FEDFUNDS))
group_df <- as.data.frame(group_df)

GSPC_df$Year <- year(GSPC_df$Date)
GSPC_group_df <- GSPC_df %>% group_by(Year) %>% 
  summarize(mean_adj_close = mean(Adj.Close))
GSPC_group_df <- as.data.frame(GSPC_group_df)

group_stats <- merge(group_df, GSPC_group_df, by = "Year", all = TRUE)
head(group_stats)
```

```{r}
#make long format, plot all stats
long_group_df <- melt(group_stats, id = "Year")

ggplot(long_group_df, aes(x = Year, y = value, color = variable)) +
  geom_line() + 
  ggtitle("Consumer Sentiment Index Compared to BLS Data & GSPC 2008 - 2022")
```

```{r}
#correlation matrix of stats
#unemployment is highly negatively correlated to the index
#other stats slightly positively correlated to the index (based on annual mean)
#all are negatively correlated to the unemployment rate
#CPI, hourly rate and adj close are very highly correlated
#fed rate is more correlated to the index than the other stats, but still just moderately
corr <- cor(group_stats[c("mean_index", "mean_hr_rate",
                          "mean_CPI", "mean_unemp",
                          "mean_fed", "mean_adj_close")])
corr
```

```{r}
#plot correlation matrix
corrplot(corr, method = 'color', col = COL2('PRGn'), diag = FALSE)
```
